# 数据预处理

## 相关设置

In [121]:
from IPython.core.interactiveshell import InteractiveShell

import pandas as pd
import numpy as np

InteractiveShell.ast_node_interactivity = "all"  # 一个cell显示多输出

pd.set_option('display.max_rows', 100)  # 设置最大显示100行
pd.set_option('display.max_columns', 100)  # 设置最大显示100列

In [122]:
Images_by_GlobalID = pd.read_excel("data/raw_data/2021MCM_ProblemC_Images_by_GlobalID.xlsx")
DataSet = pd.read_excel("data/raw_data/2021MCMProblemC_DataSet.xlsx")

S:\MathematicalModeling\MCMICM2021C\venv\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [123]:
try:
    Images_by_GlobalID.drop(labels='Unnamed: 3', axis=1, inplace=True)  # 去除最后一列的无用列
except KeyError:
    pass
Images_by_GlobalID.head()
DataSet.head()

,FileName,GlobalID,FileType
0,ATT1_DSCN9647.jpg,{5AC8034E-5B46-4294-85F0-5B13117EBEFE},image/jpg
1,ATT10_67EAF187-B59C-4F5F-BAAC-9F76E06A96D6.jpg,{C4F44511-EA53-4FCF-9422-E1C57703720D},image/jpg
2,ATT100_inbound241937372812029587.jpg,{43506835-18B8-46B2-A2CB-586AF9C8ECE6},image/jpg
3,ATT1000_A5A50BAB-A6EF-4576-A1F8-A07862AADE3A.jpg,{E0AE2F2A-38A5-463C-97B5-9F84A477F9AE},image/jpg
4,ATT1001_8B9F8599-61EF-4690-B195-888BCD319F32.png,{1CD14B56-4046-44C4-B1B8-8FB07A9071E9},image/png

,GlobalID,Detection Date,Notes,Lab Status,Lab Comments,Submission Date,Latitude,Longitude
0,{5AC8034E-5B46-4294-85F0-5B13117EBEFE},2019-12-08 00:00:00,"One dead wasp seen in Blaine, and suspect flyi...",Positive ID,,2020-01-15,48.980994,-122.688503
1,{5EAD3364-2CA7-4A39-9A53-7F9DCF5D2041},2019-10-30 00:00:00,Hornet specimen sent to WSU,Positive ID,,2020-01-15,48.971949,-122.700941
2,{13B67BCB-AFCE-4100-AD2B-76EF178BA228},2020-01-15 00:00:00,"Massive loss of bees, decapitated. No hornet s...",Unverified,,2020-01-15,48.939200,-122.661300
3,{124B9BFA-7F7B-4B8E-8A56-42E067F0F72E},2019-09-19 00:00:00,This was the colony that was found and destroy...,Positive ID,"Thanks for adding this, and the great pictures!",2020-02-04,49.149394,-123.943134
4,{BBBA5BA0-CAFB-43D3-8F1D-FB2D9CF777E0},2019-08-31 00:00:00,I was cleaning my gutters when I heard a snapp...,Unverified,Thanks for this report. I can't verify it from...,2020-02-14,48.723779,-122.354431

## 化简文件名

In [124]:
Images_by_GlobalID['FileName'] = Images_by_GlobalID['FileName'].map(lambda x: '{}.png'.format(x.split('_')[0]))
Images_by_GlobalID.head()

      FileName                                GlobalID   FileType
0     ATT1.png  {5AC8034E-5B46-4294-85F0-5B13117EBEFE}  image/jpg
1    ATT10.png  {C4F44511-EA53-4FCF-9422-E1C57703720D}  image/jpg
2   ATT100.png  {43506835-18B8-46B2-A2CB-586AF9C8ECE6}  image/jpg
3  ATT1000.png  {E0AE2F2A-38A5-463C-97B5-9F84A477F9AE}  image/jpg
4  ATT1001.png  {1CD14B56-4046-44C4-B1B8-8FB07A9071E9}  image/png

In [125]:
Images_by_GlobalID.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3305 entries, 0 to 3304
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   FileName  3305 non-null   object
 1   GlobalID  3305 non-null   object
 2   FileType  3305 non-null   object
dtypes: object(3)
memory usage: 77.6+ KB

## 制作 GlobalID-FileName 映射表

In [126]:
GlobalIDList = Images_by_GlobalID['GlobalID'].tolist()
FileNameList = Images_by_GlobalID['FileName'].tolist()
GlobalID_To_FileName_Map = dict(zip(GlobalIDList, FileNameList))

In [134]:
# print(GlobalID_To_FileName_Map)

In [135]:
DataSet['FileName'] = DataSet['GlobalID'].map(GlobalID_To_FileName_Map)

In [137]:
DataSet.head()

,GlobalID,Detection Date,Notes,Lab Status,Lab Comments,Submission Date,Latitude,Longitude,FileName
0,{5AC8034E-5B46-4294-85F0-5B13117EBEFE},2019-12-08 00:00:00,"One dead wasp seen in Blaine, and suspect flyi...",Positive ID,,2020-01-15,48.980994,-122.688503,ATT1.png
1,{5EAD3364-2CA7-4A39-9A53-7F9DCF5D2041},2019-10-30 00:00:00,Hornet specimen sent to WSU,Positive ID,,2020-01-15,48.971949,-122.700941,ATT2.png
2,{13B67BCB-AFCE-4100-AD2B-76EF178BA228},2020-01-15 00:00:00,"Massive loss of bees, decapitated. No hornet s...",Unverified,,2020-01-15,48.939200,-122.661300,ATT3.png
3,{124B9BFA-7F7B-4B8E-8A56-42E067F0F72E},2019-09-19 00:00:00,This was the colony that was found and destroy...,Positive ID,"Thanks for adding this, and the great pictures!",2020-02-04,49.149394,-123.943134,ATT7.png
4,{BBBA5BA0-CAFB-43D3-8F1D-FB2D9CF777E0},2019-08-31 00:00:00,I was cleaning my gutters when I heard a snapp...,Unverified,Thanks for this report. I can't verify it from...,2020-02-14,48.723779,-122.354431,ATT8.png

In [140]:
DataSet.to_csv("data/processed_data.csv", index=False, encoding='utf_8_sig')